flutter_launcher_icons:
  image_path: "assets/logos/wpilib_logo.png"
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
  linux:
    generate: true
  web:
    generate: true
