name: "Elastic Build"
description: "Builds Elastic for a specific platform"

inputs:
  flutter_version:
    description: "The Flutter version to download"
    required: true
  platform:
    description: "The platform for Flutter to build on"
    required: true
  is_wpilib:
    description: "Whether or not this is a WPILib build"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter_version }}
        cache: true
        cache-path: ${{ runner.tool_cache }}/flutter/${{ inputs.platform }}

    - name: Flutter Doctor
      shell: bash
      run: flutter doctor -v

    - name: Install dependencies
      shell: bash
      run: flutter pub get

    - name: Generate icons
      if: ${{ inputs.is_wpilib == 'false' }}
      shell: bash
      run: dart run flutter_launcher_icons

    - name: Generate icons (WPILib)
      if: ${{ inputs.is_wpilib == 'true' }}
      shell: bash
      run: dart run flutter_launcher_icons -f wpilib_icon_config.yaml

    - name: Build app
      shell: bash
      run: flutter build ${{ inputs.platform }} --dart-define=ELASTIC_WPILIB=${{ inputs.is_wpilib }}
