name: Compress Images
on:
  issue_comment:
    types: [ created ]

jobs:
  optimize:
    name: "Compress Images"
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/optimize')

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Switch to PR branch
        run: gh pr checkout ${{ github.event.issue.number }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Download and unpack oxipng
        run: |
          wget https://github.com/shssoichiro/oxipng/releases/download/v9.1.2/oxipng-9.1.2-x86_64-unknown-linux-gnu.tar.gz
          tar -xf oxipng-9.1.2-x86_64-unknown-linux-gnu.tar.gz
          mv oxipng-9.1.2-x86_64-unknown-linux-gnu/oxipng .

      - name: Compress images with oxipng
        run: ./oxipng -Z -o max --fast --strip safe $(git diff --name-only origin/main *.png)

      - name: Commit compressed images
        run: |
          # Set credentials
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Commit
          git commit -am "Compress images"
          git push
