name: ElasticLib

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  wpiformat-analyze:
    name: "Verify Formatting"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch all history and metadata
        run: |
          git checkout -b pr
          git branch -f main origin/main
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install wpiformat
        run: pip3 install wpiformat==2024.44
      - name: Format Java
        run: wpiformat -f Elastic.java
        working-directory: ./elasticlib
      - name: Format C++ Header
        run: wpiformat -f elasticlib.h
        working-directory: ./elasticlib
      - name: Format C++ source
        run: wpiformat -f elasticlib.cpp
        working-directory: ./elasticlib
      - name: Format Python
        run: wpiformat -f elasticlib.py
        working-directory: ./elasticlib
      - name: Check output
        run: git --no-pager diff --exit-code HEAD
